package com.shadowcraft.android;

import java.util.Arrays;
import java.util.List;

public class RealmData {
    public static final String[]   us_realms = {"aegwynn", "aerie-peak",
        "agamaggan", "aggramar", "akama", "alexstrasza", "alleria",
        "altar-of-storms", "alterac-mountains", "amanthul", "andorhal",
        "anetheron", "antonidas", "anubarak", "anvilmar", "arathor",
        "archimonde", "area-52", "argent-dawn", "arthas", "arygos",
        "auchindoun", "azgalor", "azjolnerub", "azshara", "azuremyst",
        "baelgun", "balnazzar", "barthilas", "black-dragonflight",
        "blackhand", "blackrock", "blackwater-raiders", "blackwing-lair",
        "blades-edge", "bladefist", "bleeding-hollow", "blood-furnace",
        "bloodhoof", "bloodscalp", "bonechewer", "borean-tundra",
        "boulderfist", "bronzebeard", "burning-blade", "burning-legion",
        "caelestrasz", "cairne", "cenarion-circle", "cenarius", "chogall",
        "chromaggus", "coilfang", "crushridge", "daggerspine", "dalaran",
        "dalvengyr", "dark-iron", "darkspear", "darrowmere", "dathremar",
        "dawnbringer", "deathwing", "demon-soul", "dentarg", "destromath",
        "dethecus", "detheroc", "doomhammer", "draenor", "dragonblight",
        "dragonmaw", "draktharon", "drakthul", "draka", "drakkari",
        "dreadmaul", "drenden", "dunemaul", "durotan", "duskwood",
        "earthen-ring", "echo-isles", "eitrigg", "eldrethalas", "elune",
        "emerald-dream", "eonar", "eredar", "executus", "exodar",
        "farstriders", "feathermoon", "fenris", "firetree", "fizzcrank",
        "frostmane", "frostmourne", "frostwolf", "galakrond", "garithos",
        "garona", "garrosh", "ghostlands", "gilneas", "gnomeregan",
        "gorefiend", "gorgonnash", "greymane", "grizzly-hills", "guldan",
        "gundrak", "gurubashi", "hakkar", "haomarush", "hellscream",
        "hydraxis", "hyjal", "icecrown", "illidan", "jaedenar",
        "jubeithos", "kaelthas", "kalecgos", "kargath", "kelthuzad",
        "khadgar", "khaz-modan", "khazgoroth", "kiljaeden", "kilrogg",
        "kirin-tor", "korgath", "korialstrasz", "kul-tiras",
        "laughing-skull", "lethon", "lightbringer", "lightnings-blade",
        "lightninghoof", "llane", "lothar", "madoran", "maelstrom",
        "magtheridon", "maiev", "malganis", "malfurion", "malorne",
        "malygos", "mannoroth", "medivh", "misha", "moknathal",
        "moon-guard", "moonrunner", "mugthol", "muradin", "nagrand",
        "nathrezim", "nazgrel", "nazjatar", "nerzhul", "nesingwary",
        "nordrassil", "norgannon", "onyxia", "perenolde", "proudmoore",
        "quelthalas", "queldorei", "ragnaros", "ravencrest", "ravenholdt",
        "rexxar", "rivendare", "runetotem", "sargeras", "saurfang",
        "scarlet-crusade", "scilla", "senjin", "sentinels",
        "shadow-council", "shadowmoon", "shadowsong", "shandris",
        "shattered-halls", "shattered-hand", "shuhalo", "silver-hand",
        "silvermoon", "sisters-of-elune", "skullcrusher", "skywall",
        "smolderthorn", "spinebreaker", "spirestone", "staghelm",
        "steamwheedle-cartel", "stonemaul", "stormrage", "stormreaver",
        "stormscale", "suramar", "tanaris", "terenas", "terokkar",
        "thaurissan", "the-forgotten-coast", "the-scryers", "the-underbog",
        "the-venture-co", "thorium-brotherhood", "thrall", "thunderhorn",
        "thunderlord", "tichondrius", "tortheldrin", "trollbane",
        "turalyon", "twisting-nether", "uldaman", "uldum", "undermine",
        "ursin", "uther", "vashj", "veknilash", "velen", "warsong",
        "whisperwind", "wildhammer", "windrunner", "winterhoof",
        "wyrmrest-accord", "ysera", "ysondre", "zangarmarsh", "zuljin",
    "zuluhed"                        };

    public static final String[]   eu_realms = {"aegwynn", "aerie-peak",
        "agamaggan", "aggramar", "ahnqiraj", "alakir", "alexstrasza",
        "alleria", "alonsus", "amanthul", "ambossar", "anachronos",
        "anetheron", "antonidas", "anubarak", "arakarahm", "arathi",
        "arathor", "archimonde", "area-52", "argent-dawn", "arthas",
        "arygos", "aszune", "auchindoun", "azjolnerub", "azshara",
        "azuremyst", "baelgun", "balnazzar", "blackhand", "blackmoore",
        "blackrock", "blades-edge", "bladefist", "bloodfeather",
        "bloodhoof", "bloodscalp", "blutkessel", "boulderfist",
        "bronze-dragonflight", "bronzebeard", "burning-blade",
        "burning-legion", "burning-steppes", "cthun", "chamber-of-aspects",
        "chants-eternels", "chogall", "chromaggus", "colinas-pardas",
        "confrerie-du-thorium", "conseil-des-ombres", "crushridge",
        "culte-de-la-rive-noire", "daggerspine", "dalaran", "dalvengyr",
        "darkmoon-faire", "darksorrow", "darkspear", "das-konsortium",
        "das-syndikat", "deathwing", "defias-brotherhood", "dentarg",
        "der-mithrilorden", "der-rat-von-dalaran", "der-abyssische-rat",
        "destromath", "dethecus", "die-aldor", "die-arguswacht",
        "die-nachtwache", "die-silberne-hand", "die-todeskrallen",
        "die-ewige-wacht", "doomhammer", "draenor", "dragonblight",
        "dragonmaw", "drakthul", "drekthar", "dun-modr", "dun-morogh",
        "dunemaul", "durotan", "earthen-ring", "echsenkessel", "eitrigg",
        "eldrethalas", "elune", "emerald-dream", "emeriss", "eonar",
        "eredar", "executus", "exodar", "festung-der-sturme",
        "forscherliga", "frostmane", "frostmourne", "frostwhisper",
        "frostwolf", "garona", "garrosh", "genjuros", "ghostlands",
        "gilneas", "gorgonnash", "grim-batol", "guldan", "hakkar",
        "haomarush", "hellfire", "hellscream", "hyjal", "illidan",
        "jaedenar", "kaelthas", "karazhan", "kargath", "kazzak",
        "kelthuzad", "khadgar", "khaz-modan", "khazgoroth", "kiljaeden",
        "kilrogg", "kirin-tor", "korgall", "kragjin", "krasus",
        "kul-tiras", "kult-der-verdammten", "la-croisade-ecarlate",
        "laughing-skull", "les-clairvoyants", "les-sentinelles",
        "lightbringer", "lightnings-blade", "lordaeron", "los-errantes",
        "lothar", "madmortem", "magtheridon", "malganis", "malfurion",
        "malorne", "malygos", "mannoroth", "marecage-de-zangar",
        "mazrigos", "medivh", "minahonda", "moonglade", "mugthol",
        "nagrand", "nathrezim", "naxxramas", "nazjatar", "nefarian",
        "neptulon", "nerzhul", "nerathor", "nethersturm", "nordrassil",
        "norgannon", "nozdormu", "onyxia", "outland", "perenolde",
        "proudmoore", "quelthalas", "ragnaros", "rajaxx", "rashgarroth",
        "ravencrest", "ravenholdt", "rexxar", "runetotem", "sanguino",
        "sargeras", "saurfang", "scarshield-legion", "senjin",
        "shadowsong", "shattered-halls", "shattered-hand", "shattrath",
        "shendralar", "silvermoon", "sinstralis", "skullcrusher",
        "spinebreaker", "sporeggar", "steamwheedle-cartel", "stormrage",
        "stormreaver", "stormscale", "sunstrider", "suramar", "sylvanas",
        "taerar", "talnivarr", "tarren-mill", "teldrassil", "temple-noir",
        "terenas", "terokkar", "terrordar", "the-maelstrom", "the-shatar",
        "the-venture-co", "theradras", "thrall", "throkferoth",
        "thunderhorn", "tichondrius", "tirion", "todeswache", "trollbane",
        "turalyon", "twilights-hammer", "twisting-nether", "tyrande",
        "uldaman", "ulduar", "uldum", "ungoro", "varimathras", "vashj",
        "veklor", "veknilash", "voljin", "wildhammer", "wrathbringer",
        "xavius", "ysera", "ysondre", "zenedar", "zirkel-des-cenarius",
        "zuljin", "zuluhed", "азурегос", "бореиская-тундра",
        "вечная-песня", "галакронд", "голдринн", "гордунни", "гром",
        "дракономор", "корольлич", "пиратская-бухта", "подземье",
        "разувии", "ревущии-фьорд", "свежеватель-душ", "седогрив",
        "страж-смерти", "термоштепсель", "ткач-смерти", "черныи-шрам",
    "ясеневыи-лес"                   };

    public static final String[]   kr_realms = {"가로나", "굴단", "노르간논", "달라란",
        "데스윙", "듀로탄", "라그나로스", "레인", "렉사르", "말리고스", "말퓨리온", "메디브",
        "불타는-군단", "블랙무어", "살타리온", "세나리우스", "스톰레이지", "아즈샤라", "알레리아",
        "알렉스트라자", "에이그윈", "엘룬", "와일드해머", "우서", "윈드러너", "이오나", "줄진", "카라잔",
        "카르가스", "쿨-티라스", "티리온", "하이잘", "헬스크림"};

    public static final String[]   tw_realms = {"世界之樹", "亞雷戈斯", "全球爭霸戰2",
        "冬握湖", "冰霜之刺", "冰風崗哨", "凜風峽灣", "地獄吼", "夜空之歌", "天空之牆", "奎爾達納斯",
        "奧妮克希亞", "寒冰皇冠", "尖石", "屠魔山谷", "巨龍之喉", "巴納札爾", "惡魔之魂", "憤怒使者",
        "戰歌", "提克迪奧斯", "撒爾薩里安", "日落沼澤", "暗影之月", "暴風祭壇", "死亡之翼", "水晶之刺",
        "火焰之樹", "狂心", "狂熱之刃", "狼狂索斯", "眾星之子", "科爾蘇加德", "米奈希爾", "聖光之願",
        "艾奧那斯", "血之谷", "語風", "諾姆瑞根", "遠祖灘頭", "銀翼要塞", "阿薩斯", "雷鱗", "風暴群山",
        "鬼霧峰", "黑龍軍團"                    };

    public static final String[]   cn_realms = {"万色星辰", "世界之树", "丹莫德", "主宰之剑",
        "亚雷戈斯", "亡语者", "伊兰尼库斯", "伊利丹", "伊森利恩", "伊森德雷", "伊瑟拉", "伊莫塔尔",
        "伊萨里奥斯", "元素之力", "克尔苏加德", "克洛玛古斯", "克苏恩", "军团要塞", "冬拥湖", "冬泉谷",
        "冰川之拳", "冰霜之刃", "冰风岗", "凤凰之神", "凯尔萨斯", "凯恩血蹄", "刀塔", "利刃之拳",
        "刺骨利刃", "加兹鲁维", "加基森", "加尔", "加德纳尔", "加里索斯", "勇士岛", "千针石林", "午夜之镰",
        "卡德加", "卡德罗斯", "卡扎克", "卡拉赞", "卡珊德拉", "古加尔", "古尔丹", "古拉巴什", "古达克",
        "哈兰", "哈卡", "噬灵沼泽", "嚎风峡湾", "回音山", "国王之谷", "图拉扬", "圣火神殿", "地狱之石",
        "地狱咆哮", "埃克索图斯", "埃加洛尔", "埃德萨拉", "埃苏雷格", "埃雷达尔", "基尔加丹", "基尔罗格",
        "塔纳利斯", "塞拉摩", "塞拉赞恩", "塞泰克", "塞纳里奥", "壁炉谷", "夏维安", "外域", "大地之怒",
        "大漩涡", "天空之墙", "太阳之井", "夺灵者", "奈法利安", "奎尔丹纳斯", "奎尔萨拉斯", "奥妮克希亚",
        "奥尔加隆", "奥拉基尔", "奥斯里安", "奥特兰克", "奥蕾莉亚", "奥达曼", "守护之剑", "安其拉",
        "安加萨", "安多哈尔", "安威玛尔", "安戈洛", "安格博达", "安纳塞隆", "安苏", "密林游侠", "寒冰皇冠",
        "尘风峡谷", "屠魔山谷", "山丘之王", "岩石巨塔", "巨龙之吼", "巫妖之王", "巴尔古恩", "巴瑟拉斯",
        "巴纳扎尔", "布兰卡德", "布莱克摩", "布莱恩", "布鲁塔卢斯", "希尔瓦娜斯", "希雷诺斯", "幽暗沼泽",
        "库尔提拉斯", "库德兰", "弗塞雷迦", "影之哀伤", "影牙要塞", "德拉诺", "恐怖图腾", "恶魔之翼",
        "恶魔之魂", "戈古纳斯", "戈提克", "戈杜尼", "战歌", "扎拉赞恩", "托塞德林", "托尔巴拉德",
        "拉文凯斯", "拉文霍德", "拉格纳洛斯", "拉贾克斯", "提尔之手", "提瑞斯法", "摩摩尔", "斩魔者",
        "斯坦索姆", "无尽之海", "无底海渊", "日落沼泽", "普瑞斯托", "普罗德摩", "暗影之月", "暗影议会",
        "暗影迷宫", "暮色森林", "暴风祭坛", "月光林地", "月神殿", "末日行者", "朵丹尼尔", "杜隆坦",
        "格瑞姆巴托", "格雷迈恩", "格鲁尔", "桑德兰", "梅尔加尼", "梦境之树", "森金", "死亡之翼",
        "死亡之门", "死亡熔炉", "毁灭之锤", "水晶之刺", "永夜港", "永恒之井", "法拉希姆", "泰兰德",
        "泰拉尔", "洛丹伦", "洛肯", "洛萨", "海克泰尔", "海加尔", "海达希亚", "浸毒之骨", "深渊之喉",
        "深渊之巢", "激流之傲", "激流堡", "火喉", "火烟之谷", "火焰之树", "火羽山", "灰烬使者", "灰谷",
        "烈焰峰", "烈焰荆棘", "熊猫酒仙", "熔火之心", "熵魔", "燃烧之刃", "燃烧军团", "燃烧平原",
        "爱斯特纳", "狂热之刃", "狂风峭壁", "玛克扎尔", "玛多兰", "玛格曼达", "玛格索尔", "玛法里奥",
        "玛洛加尔", "玛瑟里顿", "玛诺洛斯", "玛里苟斯", "瑞文戴尔", "瑟玛普拉格", "瑟莱德丝", "瓦丝琪",
        "瓦拉斯塔兹", "瓦里玛萨斯", "甜水绿洲", "生态船", "白银之手", "白骨荒野", "盖斯", "石爪峰", "石锤",
        "破碎大厅", "破碎岭", "祖尔金", "祖阿曼", "神圣之歌", "禁魔监狱", "穆戈尔", "符文图腾", "米奈希尔",
        "索拉丁", "索瑞森", "红云台地", "红龙军团", "红龙女王", "纳克萨玛斯", "纳沙塔尔", "织亡者",
        "维克尼拉斯", "罗宁", "羽月", "翡翠梦境", "耐克鲁斯", "耐奥祖", "耐普图隆", "耐萨里奥", "耳语海岸",
        "能源舰", "自由之风", "艾森娜", "艾欧纳尔", "艾维娜", "艾苏恩", "艾莫莉丝", "艾萨拉", "艾露恩",
        "芬里斯", "苏塔恩", "范克里夫", "范达尔鹿盔", "荆棘谷", "莉亚德琳", "莫什奥格", "莫加尔",
        "莫德雷萨", "莫格莱尼", "莱索恩", "菲拉斯", "菲米丝", "萨塔里奥", "萨尔", "萨格拉斯", "萨菲隆",
        "萨贝里安", "蒸汽地窟", "蓝龙军团", "藏宝海湾", "蜘蛛王国", "血吼", "血槌", "血牙魔王", "血环",
        "血羽", "血色十字军", "血顶", "试炼之环", "诺兹多姆", "诺森德", "诺莫瑞根", "贫瘠之地", "踏梦者",
        "轻风之语", "达克萨隆", "达基萨斯", "达尔坎", "达文格尔", "达斯雷玛", "达纳斯", "达隆米尔",
        "迅捷微风", "远古海滩", "迦拉克隆", "迦玛兰", "迦罗娜", "迦顿", "迪托马斯", "迪瑟洛克", "迪门修斯",
        "逐日者", "通灵学院", "遗忘海岸", "邪恶颅壳", "金度", "金色平原", "铜龙军团", "银月", "银松森林",
        "闪电之刃", "阿克蒙德", "阿努巴拉克", "阿卡玛", "阿古斯", "阿尔萨斯", "阿扎达斯", "阿拉希",
        "阿拉索", "阿斯塔洛", "阿曼尼", "阿格拉玛", "阿比迪斯", "阿纳克洛斯", "阿迦玛甘", "雏龙之翼",
        "雷克萨", "雷德", "雷斧堡垒", "雷霆之怒", "雷霆之王", "雷霆号角", "霍格", "霜之哀伤", "霜狼",
        "风暴之怒", "风暴之眼", "风暴之鳞", "风暴峭壁", "风暴裂隙", "风行者", "鬼雾峰", "鲜血熔炉",
        "鹰巢山", "麦姆", "麦维影歌", "麦迪文", "黄金之路", "黑手军团", "黑暗之矛", "黑暗之门", "黑暗虚空",
        "黑暗魅影", "黑石尖塔", "黑翼之巢", "黑铁", "黑锋哨站", "黑龙军团", "龙骨平原"};

    public static final String[][] names_n_slugs     = { {"Aegwynn", "aegwynn"},
        {"Aerie Peak", "aerie-peak"}, {"Agamaggan", "agamaggan"},
        {"Aggramar", "aggramar"}, {"Akama", "akama"},
        {"Alexstrasza", "alexstrasza"}, {"Alleria", "alleria"},
        {"Altar of Storms", "altar-of-storms"},
        {"Alterac Mountains", "alterac-mountains"},
        {"Aman'Thul", "amanthul"}, {"Andorhal", "andorhal"},
        {"Anetheron", "anetheron"}, {"Antonidas", "antonidas"},
        {"Anub'arak", "anubarak"}, {"Anvilmar", "anvilmar"},
        {"Arathor", "arathor"}, {"Archimonde", "archimonde"},
        {"Area 52", "area-52"}, {"Argent Dawn", "argent-dawn"},
        {"Arthas", "arthas"}, {"Arygos", "arygos"},
        {"Auchindoun", "auchindoun"}, {"Azgalor", "azgalor"},
        {"Azjol-Nerub", "azjolnerub"}, {"Azshara", "azshara"},
        {"Azuremyst", "azuremyst"}, {"Baelgun", "baelgun"},
        {"Balnazzar", "balnazzar"}, {"Barthilas", "barthilas"},
        {"Black Dragonflight", "black-dragonflight"},
        {"Blackhand", "blackhand"}, {"Blackrock", "blackrock"},
        {"Blackwater Raiders", "blackwater-raiders"},
        {"Blackwing Lair", "blackwing-lair"},
        {"Blade's Edge", "blades-edge"}, {"Bladefist", "bladefist"},
        {"Bleeding Hollow", "bleeding-hollow"},
        {"Blood Furnace", "blood-furnace"}, {"Bloodhoof", "bloodhoof"},
        {"Bloodscalp", "bloodscalp"}, {"Bonechewer", "bonechewer"},
        {"Borean Tundra", "borean-tundra"}, {"Boulderfist", "boulderfist"},
        {"Bronzebeard", "bronzebeard"}, {"Burning Blade", "burning-blade"},
        {"Burning Legion", "burning-legion"},
        {"Caelestrasz", "caelestrasz"}, {"Cairne", "cairne"},
        {"Cenarion Circle", "cenarion-circle"}, {"Cenarius", "cenarius"},
        {"Cho'gall", "chogall"}, {"Chromaggus", "chromaggus"},
        {"Coilfang", "coilfang"}, {"Crushridge", "crushridge"},
        {"Daggerspine", "daggerspine"}, {"Dalaran", "dalaran"},
        {"Dalvengyr", "dalvengyr"}, {"Dark Iron", "dark-iron"},
        {"Darkspear", "darkspear"}, {"Darrowmere", "darrowmere"},
        {"Dath'Remar", "dathremar"}, {"Dawnbringer", "dawnbringer"},
        {"Deathwing", "deathwing"}, {"Demon Soul", "demon-soul"},
        {"Dentarg", "dentarg"}, {"Destromath", "destromath"},
        {"Dethecus", "dethecus"}, {"Detheroc", "detheroc"},
        {"Doomhammer", "doomhammer"}, {"Draenor", "draenor"},
        {"Dragonblight", "dragonblight"}, {"Dragonmaw", "dragonmaw"},
        {"Drak'Tharon", "draktharon"}, {"Drak'thul", "drakthul"},
        {"Draka", "draka"}, {"Drakkari", "drakkari"},
        {"Dreadmaul", "dreadmaul"}, {"Drenden", "drenden"},
        {"Dunemaul", "dunemaul"}, {"Durotan", "durotan"},
        {"Duskwood", "duskwood"}, {"Earthen Ring", "earthen-ring"},
        {"Echo Isles", "echo-isles"}, {"Eitrigg", "eitrigg"},
        {"Eldre'Thalas", "eldrethalas"}, {"Elune", "elune"},
        {"Emerald Dream", "emerald-dream"}, {"Eonar", "eonar"},
        {"Eredar", "eredar"}, {"Executus", "executus"},
        {"Exodar", "exodar"}, {"Farstriders", "farstriders"},
        {"Feathermoon", "feathermoon"}, {"Fenris", "fenris"},
        {"Firetree", "firetree"}, {"Fizzcrank", "fizzcrank"},
        {"Frostmane", "frostmane"}, {"Frostmourne", "frostmourne"},
        {"Frostwolf", "frostwolf"}, {"Galakrond", "galakrond"},
        {"Garithos", "garithos"}, {"Garona", "garona"},
        {"Garrosh", "garrosh"}, {"Ghostlands", "ghostlands"},
        {"Gilneas", "gilneas"}, {"Gnomeregan", "gnomeregan"},
        {"Gorefiend", "gorefiend"}, {"Gorgonnash", "gorgonnash"},
        {"Greymane", "greymane"}, {"Grizzly Hills", "grizzly-hills"},
        {"Gul'dan", "guldan"}, {"Gundrak", "gundrak"},
        {"Gurubashi", "gurubashi"}, {"Hakkar", "hakkar"},
        {"Haomarush", "haomarush"}, {"Hellscream", "hellscream"},
        {"Hydraxis", "hydraxis"}, {"Hyjal", "hyjal"},
        {"Icecrown", "icecrown"}, {"Illidan", "illidan"},
        {"Jaedenar", "jaedenar"}, {"Jubei'Thos", "jubeithos"},
        {"Kael'thas", "kaelthas"}, {"Kalecgos", "kalecgos"},
        {"Kargath", "kargath"}, {"Kel'Thuzad", "kelthuzad"},
        {"Khadgar", "khadgar"}, {"Khaz Modan", "khaz-modan"},
        {"Khaz'goroth", "khazgoroth"}, {"Kil'jaeden", "kiljaeden"},
        {"Kilrogg", "kilrogg"}, {"Kirin Tor", "kirin-tor"},
        {"Korgath", "korgath"}, {"Korialstrasz", "korialstrasz"},
        {"Kul Tiras", "kul-tiras"}, {"Laughing Skull", "laughing-skull"},
        {"Lethon", "lethon"}, {"Lightbringer", "lightbringer"},
        {"Lightning's Blade", "lightnings-blade"},
        {"Lightninghoof", "lightninghoof"}, {"Llane", "llane"},
        {"Lothar", "lothar"}, {"Madoran", "madoran"},
        {"Maelstrom", "maelstrom"}, {"Magtheridon", "magtheridon"},
        {"Maiev", "maiev"}, {"Mal'Ganis", "malganis"},
        {"Malfurion", "malfurion"}, {"Malorne", "malorne"},
        {"Malygos", "malygos"}, {"Mannoroth", "mannoroth"},
        {"Medivh", "medivh"}, {"Misha", "misha"},
        {"Mok'Nathal", "moknathal"}, {"Moon Guard", "moon-guard"},
        {"Moonrunner", "moonrunner"}, {"Mug'thol", "mugthol"},
        {"Muradin", "muradin"}, {"Nagrand", "nagrand"},
        {"Nathrezim", "nathrezim"}, {"Nazgrel", "nazgrel"},
        {"Nazjatar", "nazjatar"}, {"Ner'zhul", "nerzhul"},
        {"Nesingwary", "nesingwary"}, {"Nordrassil", "nordrassil"},
        {"Norgannon", "norgannon"}, {"Onyxia", "onyxia"},
        {"Perenolde", "perenolde"}, {"Proudmoore", "proudmoore"},
        {"Quel'Thalas", "quelthalas"}, {"Quel'dorei", "queldorei"},
        {"Ragnaros", "ragnaros"}, {"Ravencrest", "ravencrest"},
        {"Ravenholdt", "ravenholdt"}, {"Rexxar", "rexxar"},
        {"Rivendare", "rivendare"}, {"Runetotem", "runetotem"},
        {"Sargeras", "sargeras"}, {"Saurfang", "saurfang"},
        {"Scarlet Crusade", "scarlet-crusade"}, {"Scilla", "scilla"},
        {"Sen'jin", "senjin"}, {"Sentinels", "sentinels"},
        {"Shadow Council", "shadow-council"}, {"Shadowmoon", "shadowmoon"},
        {"Shadowsong", "shadowsong"}, {"Shandris", "shandris"},
        {"Shattered Halls", "shattered-halls"},
        {"Shattered Hand", "shattered-hand"}, {"Shu'halo", "shuhalo"},
        {"Silver Hand", "silver-hand"}, {"Silvermoon", "silvermoon"},
        {"Sisters of Elune", "sisters-of-elune"},
        {"Skullcrusher", "skullcrusher"}, {"Skywall", "skywall"},
        {"Smolderthorn", "smolderthorn"}, {"Spinebreaker", "spinebreaker"},
        {"Spirestone", "spirestone"}, {"Staghelm", "staghelm"},
        {"Steamwheedle Cartel", "steamwheedle-cartel"},
        {"Stonemaul", "stonemaul"}, {"Stormrage", "stormrage"},
        {"Stormreaver", "stormreaver"}, {"Stormscale", "stormscale"},
        {"Suramar", "suramar"}, {"Tanaris", "tanaris"},
        {"Terenas", "terenas"}, {"Terokkar", "terokkar"},
        {"Thaurissan", "thaurissan"},
        {"The Forgotten Coast", "the-forgotten-coast"},
        {"The Scryers", "the-scryers"}, {"The Underbog", "the-underbog"},
        {"The Venture Co", "the-venture-co"},
        {"Thorium Brotherhood", "thorium-brotherhood"},
        {"Thrall", "thrall"}, {"Thunderhorn", "thunderhorn"},
        {"Thunderlord", "thunderlord"}, {"Tichondrius", "tichondrius"},
        {"Tortheldrin", "tortheldrin"}, {"Trollbane", "trollbane"},
        {"Turalyon", "turalyon"}, {"Twisting Nether", "twisting-nether"},
        {"Uldaman", "uldaman"}, {"Uldum", "uldum"},
        {"Undermine", "undermine"}, {"Ursin", "ursin"}, {"Uther", "uther"},
        {"Vashj", "vashj"}, {"Vek'nilash", "veknilash"},
        {"Velen", "velen"}, {"Warsong", "warsong"},
        {"Whisperwind", "whisperwind"}, {"Wildhammer", "wildhammer"},
        {"Windrunner", "windrunner"}, {"Winterhoof", "winterhoof"},
        {"Wyrmrest Accord", "wyrmrest-accord"}, {"Ysera", "ysera"},
        {"Ysondre", "ysondre"}, {"Zangarmarsh", "zangarmarsh"},
        {"Zul'jin", "zuljin"}, {"Zuluhed", "zuluhed"},
        {"Aegwynn", "aegwynn"}, {"Aerie Peak", "aerie-peak"},
        {"Agamaggan", "agamaggan"}, {"Aggramar", "aggramar"},
        {"Ahn'Qiraj", "ahnqiraj"}, {"Al'Akir", "alakir"},
        {"Alexstrasza", "alexstrasza"}, {"Alleria", "alleria"},
        {"Alonsus", "alonsus"}, {"Aman'Thul", "amanthul"},
        {"Ambossar", "ambossar"}, {"Anachronos", "anachronos"},
        {"Anetheron", "anetheron"}, {"Antonidas", "antonidas"},
        {"Anub'arak", "anubarak"}, {"Arak-arahm", "arakarahm"},
        {"Arathi", "arathi"}, {"Arathor", "arathor"},
        {"Archimonde", "archimonde"}, {"Area 52", "area-52"},
        {"Argent Dawn", "argent-dawn"}, {"Arthas", "arthas"},
        {"Arygos", "arygos"}, {"Aszune", "aszune"},
        {"Auchindoun", "auchindoun"}, {"Azjol-Nerub", "azjolnerub"},
        {"Azshara", "azshara"}, {"Azuremyst", "azuremyst"},
        {"Baelgun", "baelgun"}, {"Balnazzar", "balnazzar"},
        {"Blackhand", "blackhand"}, {"Blackmoore", "blackmoore"},
        {"Blackrock", "blackrock"}, {"Blade's Edge", "blades-edge"},
        {"Bladefist", "bladefist"}, {"Bloodfeather", "bloodfeather"},
        {"Bloodhoof", "bloodhoof"}, {"Bloodscalp", "bloodscalp"},
        {"Blutkessel", "blutkessel"}, {"Boulderfist", "boulderfist"},
        {"Bronze Dragonflight", "bronze-dragonflight"},
        {"Bronzebeard", "bronzebeard"}, {"Burning Blade", "burning-blade"},
        {"Burning Legion", "burning-legion"},
        {"Burning Steppes", "burning-steppes"}, {"C'Thun", "cthun"},
        {"Chamber of Aspects", "chamber-of-aspects"},
        {"Chants éternels", "chants-eternels"}, {"Cho'gall", "chogall"},
        {"Chromaggus", "chromaggus"}, {"Colinas Pardas", "colinas-pardas"},
        {"Confrérie du Thorium", "confrerie-du-thorium"},
        {"Conseil des Ombres", "conseil-des-ombres"},
        {"Crushridge", "crushridge"},
        {"Culte de la Rive noire", "culte-de-la-rive-noire"},
        {"Daggerspine", "daggerspine"}, {"Dalaran", "dalaran"},
        {"Dalvengyr", "dalvengyr"}, {"Darkmoon Faire", "darkmoon-faire"},
        {"Darksorrow", "darksorrow"}, {"Darkspear", "darkspear"},
        {"Das Konsortium", "das-konsortium"},
        {"Das Syndikat", "das-syndikat"}, {"Deathwing", "deathwing"},
        {"Defias Brotherhood", "defias-brotherhood"},
        {"Dentarg", "dentarg"}, {"Der Mithrilorden", "der-mithrilorden"},
        {"Der Rat von Dalaran", "der-rat-von-dalaran"},
        {"Der abyssische Rat", "der-abyssische-rat"},
        {"Destromath", "destromath"}, {"Dethecus", "dethecus"},
        {"Die Aldor", "die-aldor"}, {"Die Arguswacht", "die-arguswacht"},
        {"Die Nachtwache", "die-nachtwache"},
        {"Die Silberne Hand", "die-silberne-hand"},
        {"Die Todeskrallen", "die-todeskrallen"},
        {"Die ewige Wacht", "die-ewige-wacht"},
        {"Doomhammer", "doomhammer"}, {"Draenor", "draenor"},
        {"Dragonblight", "dragonblight"}, {"Dragonmaw", "dragonmaw"},
        {"Drak'thul", "drakthul"}, {"Drek'Thar", "drekthar"},
        {"Dun Modr", "dun-modr"}, {"Dun Morogh", "dun-morogh"},
        {"Dunemaul", "dunemaul"}, {"Durotan", "durotan"},
        {"Earthen Ring", "earthen-ring"}, {"Echsenkessel", "echsenkessel"},
        {"Eitrigg", "eitrigg"}, {"Eldre'Thalas", "eldrethalas"},
        {"Elune", "elune"}, {"Emerald Dream", "emerald-dream"},
        {"Emeriss", "emeriss"}, {"Eonar", "eonar"}, {"Eredar", "eredar"},
        {"Executus", "executus"}, {"Exodar", "exodar"},
        {"Festung der Stürme", "festung-der-sturme"},
        {"Forscherliga", "forscherliga"}, {"Frostmane", "frostmane"},
        {"Frostmourne", "frostmourne"}, {"Frostwhisper", "frostwhisper"},
        {"Frostwolf", "frostwolf"}, {"Garona", "garona"},
        {"Garrosh", "garrosh"}, {"Genjuros", "genjuros"},
        {"Ghostlands", "ghostlands"}, {"Gilneas", "gilneas"},
        {"Gorgonnash", "gorgonnash"}, {"Grim Batol", "grim-batol"},
        {"Gul'dan", "guldan"}, {"Hakkar", "hakkar"},
        {"Haomarush", "haomarush"}, {"Hellfire", "hellfire"},
        {"Hellscream", "hellscream"}, {"Hyjal", "hyjal"},
        {"Illidan", "illidan"}, {"Jaedenar", "jaedenar"},
        {"Kael'thas", "kaelthas"}, {"Karazhan", "karazhan"},
        {"Kargath", "kargath"}, {"Kazzak", "kazzak"},
        {"Kel'Thuzad", "kelthuzad"}, {"Khadgar", "khadgar"},
        {"Khaz Modan", "khaz-modan"}, {"Khaz'goroth", "khazgoroth"},
        {"Kil'jaeden", "kiljaeden"}, {"Kilrogg", "kilrogg"},
        {"Kirin Tor", "kirin-tor"}, {"Kor'gall", "korgall"},
        {"Krag'jin", "kragjin"}, {"Krasus", "krasus"},
        {"Kul Tiras", "kul-tiras"},
        {"Kult der Verdammten", "kult-der-verdammten"},
        {"La Croisade écarlate", "la-croisade-ecarlate"},
        {"Laughing Skull", "laughing-skull"},
        {"Les Clairvoyants", "les-clairvoyants"},
        {"Les Sentinelles", "les-sentinelles"},
        {"Lightbringer", "lightbringer"},
        {"Lightning's Blade", "lightnings-blade"},
        {"Lordaeron", "lordaeron"}, {"Los Errantes", "los-errantes"},
        {"Lothar", "lothar"}, {"Madmortem", "madmortem"},
        {"Magtheridon", "magtheridon"}, {"Mal'Ganis", "malganis"},
        {"Malfurion", "malfurion"}, {"Malorne", "malorne"},
        {"Malygos", "malygos"}, {"Mannoroth", "mannoroth"},
        {"Marécage de Zangar", "marecage-de-zangar"},
        {"Mazrigos", "mazrigos"}, {"Medivh", "medivh"},
        {"Minahonda", "minahonda"}, {"Moonglade", "moonglade"},
        {"Mug'thol", "mugthol"}, {"Nagrand", "nagrand"},
        {"Nathrezim", "nathrezim"}, {"Naxxramas", "naxxramas"},
        {"Nazjatar", "nazjatar"}, {"Nefarian", "nefarian"},
        {"Neptulon", "neptulon"}, {"Ner'zhul", "nerzhul"},
        {"Nera'thor", "nerathor"}, {"Nethersturm", "nethersturm"},
        {"Nordrassil", "nordrassil"}, {"Norgannon", "norgannon"},
        {"Nozdormu", "nozdormu"}, {"Onyxia", "onyxia"},
        {"Outland", "outland"}, {"Perenolde", "perenolde"},
        {"Proudmoore", "proudmoore"}, {"Quel'Thalas", "quelthalas"},
        {"Ragnaros", "ragnaros"}, {"Rajaxx", "rajaxx"},
        {"Rashgarroth", "rashgarroth"}, {"Ravencrest", "ravencrest"},
        {"Ravenholdt", "ravenholdt"}, {"Rexxar", "rexxar"},
        {"Runetotem", "runetotem"}, {"Sanguino", "sanguino"},
        {"Sargeras", "sargeras"}, {"Saurfang", "saurfang"},
        {"Scarshield Legion", "scarshield-legion"}, {"Sen'jin", "senjin"},
        {"Shadowsong", "shadowsong"},
        {"Shattered Halls", "shattered-halls"},
        {"Shattered Hand", "shattered-hand"}, {"Shattrath", "shattrath"},
        {"Shen'dralar", "shendralar"}, {"Silvermoon", "silvermoon"},
        {"Sinstralis", "sinstralis"}, {"Skullcrusher", "skullcrusher"},
        {"Spinebreaker", "spinebreaker"}, {"Sporeggar", "sporeggar"},
        {"Steamwheedle Cartel", "steamwheedle-cartel"},
        {"Stormrage", "stormrage"}, {"Stormreaver", "stormreaver"},
        {"Stormscale", "stormscale"}, {"Sunstrider", "sunstrider"},
        {"Suramar", "suramar"}, {"Sylvanas", "sylvanas"},
        {"Taerar", "taerar"}, {"Talnivarr", "talnivarr"},
        {"Tarren Mill", "tarren-mill"}, {"Teldrassil", "teldrassil"},
        {"Temple noir", "temple-noir"}, {"Terenas", "terenas"},
        {"Terokkar", "terokkar"}, {"Terrordar", "terrordar"},
        {"The Maelstrom", "the-maelstrom"}, {"The Sha'tar", "the-shatar"},
        {"The Venture Co", "the-venture-co"}, {"Theradras", "theradras"},
        {"Thrall", "thrall"}, {"Throk'Feroth", "throkferoth"},
        {"Thunderhorn", "thunderhorn"}, {"Tichondrius", "tichondrius"},
        {"Tirion", "tirion"}, {"Todeswache", "todeswache"},
        {"Trollbane", "trollbane"}, {"Turalyon", "turalyon"},
        {"Twilight's Hammer", "twilights-hammer"},
        {"Twisting Nether", "twisting-nether"}, {"Tyrande", "tyrande"},
        {"Uldaman", "uldaman"}, {"Ulduar", "ulduar"}, {"Uldum", "uldum"},
        {"Un'Goro", "ungoro"}, {"Varimathras", "varimathras"},
        {"Vashj", "vashj"}, {"Vek'lor", "veklor"},
        {"Vek'nilash", "veknilash"}, {"Vol'jin", "voljin"},
        {"Wildhammer", "wildhammer"}, {"Wrathbringer", "wrathbringer"},
        {"Xavius", "xavius"}, {"Ysera", "ysera"}, {"Ysondre", "ysondre"},
        {"Zenedar", "zenedar"},
        {"Zirkel des Cenarius", "zirkel-des-cenarius"},
        {"Zul'jin", "zuljin"}, {"Zuluhed", "zuluhed"},
        {"Азурегос", "азурегос"}, {"Борейская тундра", "бореиская-тундра"},
        {"Вечная Песня", "вечная-песня"}, {"Галакронд", "галакронд"},
        {"Голдринн", "голдринн"}, {"Гордунни", "гордунни"},
        {"Гром", "гром"}, {"Дракономор", "дракономор"},
        {"Король-лич", "корольлич"},
        {"Пиратская бухта", "пиратская-бухта"}, {"Подземье", "подземье"},
        {"Разувий", "разувии"}, {"Ревущий фьорд", "ревущии-фьорд"},
        {"Свежеватель Душ", "свежеватель-душ"}, {"Седогрив", "седогрив"},
        {"Страж Смерти", "страж-смерти"},
        {"Термоштепсель", "термоштепсель"}, {"Ткач Смерти", "ткач-смерти"},
        {"Черный Шрам", "черныи-шрам"}, {"Ясеневый лес", "ясеневыи-лес"},
        {"가로나", "가로나"}, {"굴단", "굴단"}, {"노르간논", "노르간논"}, {"달라란", "달라란"},
        {"데스윙", "데스윙"}, {"듀로탄", "듀로탄"}, {"라그나로스", "라그나로스"}, {"레인", "레인"},
        {"렉사르", "렉사르"}, {"말리고스", "말리고스"}, {"말퓨리온", "말퓨리온"}, {"메디브", "메디브"},
        {"불타는 군단", "불타는-군단"}, {"블랙무어", "블랙무어"}, {"살타리온", "살타리온"},
        {"세나리우스", "세나리우스"}, {"스톰레이지", "스톰레이지"}, {"아즈샤라", "아즈샤라"},
        {"알레리아", "알레리아"}, {"알렉스트라자", "알렉스트라자"}, {"에이그윈", "에이그윈"},
        {"엘룬", "엘룬"}, {"와일드해머", "와일드해머"}, {"우서", "우서"}, {"윈드러너", "윈드러너"},
        {"이오나", "이오나"}, {"줄진", "줄진"}, {"카라잔", "카라잔"}, {"카르가스", "카르가스"},
        {"쿨 티라스", "쿨-티라스"}, {"티리온", "티리온"}, {"하이잘", "하이잘"},
        {"헬스크림", "헬스크림"}, {"世界之樹", "世界之樹"}, {"亞雷戈斯", "亞雷戈斯"},
        {"全球爭霸戰2", "全球爭霸戰2"}, {"冬握湖", "冬握湖"}, {"冰霜之刺", "冰霜之刺"},
        {"冰風崗哨", "冰風崗哨"}, {"凜風峽灣", "凜風峽灣"}, {"地獄吼", "地獄吼"},
        {"夜空之歌", "夜空之歌"}, {"天空之牆", "天空之牆"}, {"奎爾達納斯", "奎爾達納斯"},
        {"奧妮克希亞", "奧妮克希亞"}, {"寒冰皇冠", "寒冰皇冠"}, {"尖石", "尖石"},
        {"屠魔山谷", "屠魔山谷"}, {"巨龍之喉", "巨龍之喉"}, {"巴納札爾", "巴納札爾"},
        {"惡魔之魂", "惡魔之魂"}, {"憤怒使者", "憤怒使者"}, {"戰歌", "戰歌"},
        {"提克迪奧斯", "提克迪奧斯"}, {"撒爾薩里安", "撒爾薩里安"}, {"日落沼澤", "日落沼澤"},
        {"暗影之月", "暗影之月"}, {"暴風祭壇", "暴風祭壇"}, {"死亡之翼", "死亡之翼"},
        {"水晶之刺", "水晶之刺"}, {"火焰之樹", "火焰之樹"}, {"狂心", "狂心"}, {"狂熱之刃", "狂熱之刃"},
        {"狼狂索斯", "狼狂索斯"}, {"眾星之子", "眾星之子"}, {"科爾蘇加德", "科爾蘇加德"},
        {"米奈希爾", "米奈希爾"}, {"聖光之願", "聖光之願"}, {"艾奧那斯", "艾奧那斯"},
        {"血之谷", "血之谷"}, {"語風", "語風"}, {"諾姆瑞根", "諾姆瑞根"}, {"遠祖灘頭", "遠祖灘頭"},
        {"銀翼要塞", "銀翼要塞"}, {"阿薩斯", "阿薩斯"}, {"雷鱗", "雷鱗"}, {"風暴群山", "風暴群山"},
        {"鬼霧峰", "鬼霧峰"}, {"黑龍軍團", "黑龍軍團"}, {"万色星辰", "万色星辰"},
        {"世界之树", "世界之树"}, {"丹莫德", "丹莫德"}, {"主宰之剑", "主宰之剑"},
        {"亚雷戈斯", "亚雷戈斯"}, {"亡语者", "亡语者"}, {"伊兰尼库斯", "伊兰尼库斯"},
        {"伊利丹", "伊利丹"}, {"伊森利恩", "伊森利恩"}, {"伊森德雷", "伊森德雷"}, {"伊瑟拉", "伊瑟拉"},
        {"伊莫塔尔", "伊莫塔尔"}, {"伊萨里奥斯", "伊萨里奥斯"}, {"元素之力", "元素之力"},
        {"克尔苏加德", "克尔苏加德"}, {"克洛玛古斯", "克洛玛古斯"}, {"克苏恩", "克苏恩"},
        {"军团要塞", "军团要塞"}, {"冬拥湖", "冬拥湖"}, {"冬泉谷", "冬泉谷"}, {"冰川之拳", "冰川之拳"},
        {"冰霜之刃", "冰霜之刃"}, {"冰风岗", "冰风岗"}, {"凤凰之神", "凤凰之神"},
        {"凯尔萨斯", "凯尔萨斯"}, {"凯恩血蹄", "凯恩血蹄"}, {"刀塔", "刀塔"}, {"利刃之拳", "利刃之拳"},
        {"刺骨利刃", "刺骨利刃"}, {"加兹鲁维", "加兹鲁维"}, {"加基森", "加基森"}, {"加尔", "加尔"},
        {"加德纳尔", "加德纳尔"}, {"加里索斯", "加里索斯"}, {"勇士岛", "勇士岛"},
        {"千针石林", "千针石林"}, {"午夜之镰", "午夜之镰"}, {"卡德加", "卡德加"},
        {"卡德罗斯", "卡德罗斯"}, {"卡扎克", "卡扎克"}, {"卡拉赞", "卡拉赞"}, {"卡珊德拉", "卡珊德拉"},
        {"古加尔", "古加尔"}, {"古尔丹", "古尔丹"}, {"古拉巴什", "古拉巴什"}, {"古达克", "古达克"},
        {"哈兰", "哈兰"}, {"哈卡", "哈卡"}, {"噬灵沼泽", "噬灵沼泽"}, {"嚎风峡湾", "嚎风峡湾"},
        {"回音山", "回音山"}, {"国王之谷", "国王之谷"}, {"图拉扬", "图拉扬"}, {"圣火神殿", "圣火神殿"},
        {"地狱之石", "地狱之石"}, {"地狱咆哮", "地狱咆哮"}, {"埃克索图斯", "埃克索图斯"},
        {"埃加洛尔", "埃加洛尔"}, {"埃德萨拉", "埃德萨拉"}, {"埃苏雷格", "埃苏雷格"},
        {"埃雷达尔", "埃雷达尔"}, {"基尔加丹", "基尔加丹"}, {"基尔罗格", "基尔罗格"},
        {"塔纳利斯", "塔纳利斯"}, {"塞拉摩", "塞拉摩"}, {"塞拉赞恩", "塞拉赞恩"}, {"塞泰克", "塞泰克"},
        {"塞纳里奥", "塞纳里奥"}, {"壁炉谷", "壁炉谷"}, {"夏维安", "夏维安"}, {"外域", "外域"},
        {"大地之怒", "大地之怒"}, {"大漩涡", "大漩涡"}, {"天空之墙", "天空之墙"},
        {"太阳之井", "太阳之井"}, {"夺灵者", "夺灵者"}, {"奈法利安", "奈法利安"},
        {"奎尔丹纳斯", "奎尔丹纳斯"}, {"奎尔萨拉斯", "奎尔萨拉斯"}, {"奥妮克希亚", "奥妮克希亚"},
        {"奥尔加隆", "奥尔加隆"}, {"奥拉基尔", "奥拉基尔"}, {"奥斯里安", "奥斯里安"},
        {"奥特兰克", "奥特兰克"}, {"奥蕾莉亚", "奥蕾莉亚"}, {"奥达曼", "奥达曼"},
        {"守护之剑", "守护之剑"}, {"安其拉", "安其拉"}, {"安加萨", "安加萨"}, {"安多哈尔", "安多哈尔"},
        {"安威玛尔", "安威玛尔"}, {"安戈洛", "安戈洛"}, {"安格博达", "安格博达"},
        {"安纳塞隆", "安纳塞隆"}, {"安苏", "安苏"}, {"密林游侠", "密林游侠"}, {"寒冰皇冠", "寒冰皇冠"},
        {"尘风峡谷", "尘风峡谷"}, {"屠魔山谷", "屠魔山谷"}, {"山丘之王", "山丘之王"},
        {"岩石巨塔", "岩石巨塔"}, {"巨龙之吼", "巨龙之吼"}, {"巫妖之王", "巫妖之王"},
        {"巴尔古恩", "巴尔古恩"}, {"巴瑟拉斯", "巴瑟拉斯"}, {"巴纳扎尔", "巴纳扎尔"},
        {"布兰卡德", "布兰卡德"}, {"布莱克摩", "布莱克摩"}, {"布莱恩", "布莱恩"},
        {"布鲁塔卢斯", "布鲁塔卢斯"}, {"希尔瓦娜斯", "希尔瓦娜斯"}, {"希雷诺斯", "希雷诺斯"},
        {"幽暗沼泽", "幽暗沼泽"}, {"库尔提拉斯", "库尔提拉斯"}, {"库德兰", "库德兰"},
        {"弗塞雷迦", "弗塞雷迦"}, {"影之哀伤", "影之哀伤"}, {"影牙要塞", "影牙要塞"},
        {"德拉诺", "德拉诺"}, {"恐怖图腾", "恐怖图腾"}, {"恶魔之翼", "恶魔之翼"},
        {"恶魔之魂", "恶魔之魂"}, {"戈古纳斯", "戈古纳斯"}, {"戈提克", "戈提克"}, {"戈杜尼", "戈杜尼"},
        {"战歌", "战歌"}, {"扎拉赞恩", "扎拉赞恩"}, {"托塞德林", "托塞德林"},
        {"托尔巴拉德", "托尔巴拉德"}, {"拉文凯斯", "拉文凯斯"}, {"拉文霍德", "拉文霍德"},
        {"拉格纳洛斯", "拉格纳洛斯"}, {"拉贾克斯", "拉贾克斯"}, {"提尔之手", "提尔之手"},
        {"提瑞斯法", "提瑞斯法"}, {"摩摩尔", "摩摩尔"}, {"斩魔者", "斩魔者"}, {"斯坦索姆", "斯坦索姆"},
        {"无尽之海", "无尽之海"}, {"无底海渊", "无底海渊"}, {"日落沼泽", "日落沼泽"},
        {"普瑞斯托", "普瑞斯托"}, {"普罗德摩", "普罗德摩"}, {"暗影之月", "暗影之月"},
        {"暗影议会", "暗影议会"}, {"暗影迷宫", "暗影迷宫"}, {"暮色森林", "暮色森林"},
        {"暴风祭坛", "暴风祭坛"}, {"月光林地", "月光林地"}, {"月神殿", "月神殿"},
        {"末日行者", "末日行者"}, {"朵丹尼尔", "朵丹尼尔"}, {"杜隆坦", "杜隆坦"},
        {"格瑞姆巴托", "格瑞姆巴托"}, {"格雷迈恩", "格雷迈恩"}, {"格鲁尔", "格鲁尔"},
        {"桑德兰", "桑德兰"}, {"梅尔加尼", "梅尔加尼"}, {"梦境之树", "梦境之树"}, {"森金", "森金"},
        {"死亡之翼", "死亡之翼"}, {"死亡之门", "死亡之门"}, {"死亡熔炉", "死亡熔炉"},
        {"毁灭之锤", "毁灭之锤"}, {"水晶之刺", "水晶之刺"}, {"永夜港", "永夜港"},
        {"永恒之井", "永恒之井"}, {"法拉希姆", "法拉希姆"}, {"泰兰德", "泰兰德"}, {"泰拉尔", "泰拉尔"},
        {"洛丹伦", "洛丹伦"}, {"洛肯", "洛肯"}, {"洛萨", "洛萨"}, {"海克泰尔", "海克泰尔"},
        {"海加尔", "海加尔"}, {"海达希亚", "海达希亚"}, {"浸毒之骨", "浸毒之骨"},
        {"深渊之喉", "深渊之喉"}, {"深渊之巢", "深渊之巢"}, {"激流之傲", "激流之傲"},
        {"激流堡", "激流堡"}, {"火喉", "火喉"}, {"火烟之谷", "火烟之谷"}, {"火焰之树", "火焰之树"},
        {"火羽山", "火羽山"}, {"灰烬使者", "灰烬使者"}, {"灰谷", "灰谷"}, {"烈焰峰", "烈焰峰"},
        {"烈焰荆棘", "烈焰荆棘"}, {"熊猫酒仙", "熊猫酒仙"}, {"熔火之心", "熔火之心"}, {"熵魔", "熵魔"},
        {"燃烧之刃", "燃烧之刃"}, {"燃烧军团", "燃烧军团"}, {"燃烧平原", "燃烧平原"},
        {"爱斯特纳", "爱斯特纳"}, {"狂热之刃", "狂热之刃"}, {"狂风峭壁", "狂风峭壁"},
        {"玛克扎尔", "玛克扎尔"}, {"玛多兰", "玛多兰"}, {"玛格曼达", "玛格曼达"},
        {"玛格索尔", "玛格索尔"}, {"玛法里奥", "玛法里奥"}, {"玛洛加尔", "玛洛加尔"},
        {"玛瑟里顿", "玛瑟里顿"}, {"玛诺洛斯", "玛诺洛斯"}, {"玛里苟斯", "玛里苟斯"},
        {"瑞文戴尔", "瑞文戴尔"}, {"瑟玛普拉格", "瑟玛普拉格"}, {"瑟莱德丝", "瑟莱德丝"},
        {"瓦丝琪", "瓦丝琪"}, {"瓦拉斯塔兹", "瓦拉斯塔兹"}, {"瓦里玛萨斯", "瓦里玛萨斯"},
        {"甜水绿洲", "甜水绿洲"}, {"生态船", "生态船"}, {"白银之手", "白银之手"},
        {"白骨荒野", "白骨荒野"}, {"盖斯", "盖斯"}, {"石爪峰", "石爪峰"}, {"石锤", "石锤"},
        {"破碎大厅", "破碎大厅"}, {"破碎岭", "破碎岭"}, {"祖尔金", "祖尔金"}, {"祖阿曼", "祖阿曼"},
        {"神圣之歌", "神圣之歌"}, {"禁魔监狱", "禁魔监狱"}, {"穆戈尔", "穆戈尔"},
        {"符文图腾", "符文图腾"}, {"米奈希尔", "米奈希尔"}, {"索拉丁", "索拉丁"}, {"索瑞森", "索瑞森"},
        {"红云台地", "红云台地"}, {"红龙军团", "红龙军团"}, {"红龙女王", "红龙女王"},
        {"纳克萨玛斯", "纳克萨玛斯"}, {"纳沙塔尔", "纳沙塔尔"}, {"织亡者", "织亡者"},
        {"维克尼拉斯", "维克尼拉斯"}, {"罗宁", "罗宁"}, {"羽月", "羽月"}, {"翡翠梦境", "翡翠梦境"},
        {"耐克鲁斯", "耐克鲁斯"}, {"耐奥祖", "耐奥祖"}, {"耐普图隆", "耐普图隆"},
        {"耐萨里奥", "耐萨里奥"}, {"耳语海岸", "耳语海岸"}, {"能源舰", "能源舰"},
        {"自由之风", "自由之风"}, {"艾森娜", "艾森娜"}, {"艾欧纳尔", "艾欧纳尔"}, {"艾维娜", "艾维娜"},
        {"艾苏恩", "艾苏恩"}, {"艾莫莉丝", "艾莫莉丝"}, {"艾萨拉", "艾萨拉"}, {"艾露恩", "艾露恩"},
        {"芬里斯", "芬里斯"}, {"苏塔恩", "苏塔恩"}, {"范克里夫", "范克里夫"},
        {"范达尔鹿盔", "范达尔鹿盔"}, {"荆棘谷", "荆棘谷"}, {"莉亚德琳", "莉亚德琳"},
        {"莫什奥格", "莫什奥格"}, {"莫加尔", "莫加尔"}, {"莫德雷萨", "莫德雷萨"},
        {"莫格莱尼", "莫格莱尼"}, {"莱索恩", "莱索恩"}, {"菲拉斯", "菲拉斯"}, {"菲米丝", "菲米丝"},
        {"萨塔里奥", "萨塔里奥"}, {"萨尔", "萨尔"}, {"萨格拉斯", "萨格拉斯"}, {"萨菲隆", "萨菲隆"},
        {"萨贝里安", "萨贝里安"}, {"蒸汽地窟", "蒸汽地窟"}, {"蓝龙军团", "蓝龙军团"},
        {"藏宝海湾", "藏宝海湾"}, {"蜘蛛王国", "蜘蛛王国"}, {"血吼", "血吼"}, {"血槌", "血槌"},
        {"血牙魔王", "血牙魔王"}, {"血环", "血环"}, {"血羽", "血羽"}, {"血色十字军", "血色十字军"},
        {"血顶", "血顶"}, {"试炼之环", "试炼之环"}, {"诺兹多姆", "诺兹多姆"}, {"诺森德", "诺森德"},
        {"诺莫瑞根", "诺莫瑞根"}, {"贫瘠之地", "贫瘠之地"}, {"踏梦者", "踏梦者"},
        {"轻风之语", "轻风之语"}, {"达克萨隆", "达克萨隆"}, {"达基萨斯", "达基萨斯"},
        {"达尔坎", "达尔坎"}, {"达文格尔", "达文格尔"}, {"达斯雷玛", "达斯雷玛"}, {"达纳斯", "达纳斯"},
        {"达隆米尔", "达隆米尔"}, {"迅捷微风", "迅捷微风"}, {"远古海滩", "远古海滩"},
        {"迦拉克隆", "迦拉克隆"}, {"迦玛兰", "迦玛兰"}, {"迦罗娜", "迦罗娜"}, {"迦顿", "迦顿"},
        {"迪托马斯", "迪托马斯"}, {"迪瑟洛克", "迪瑟洛克"}, {"迪门修斯", "迪门修斯"},
        {"逐日者", "逐日者"}, {"通灵学院", "通灵学院"}, {"遗忘海岸", "遗忘海岸"},
        {"邪恶颅壳", "邪恶颅壳"}, {"金度", "金度"}, {"金色平原", "金色平原"}, {"铜龙军团", "铜龙军团"},
        {"银月", "银月"}, {"银松森林", "银松森林"}, {"闪电之刃", "闪电之刃"}, {"阿克蒙德", "阿克蒙德"},
        {"阿努巴拉克", "阿努巴拉克"}, {"阿卡玛", "阿卡玛"}, {"阿古斯", "阿古斯"},
        {"阿尔萨斯", "阿尔萨斯"}, {"阿扎达斯", "阿扎达斯"}, {"阿拉希", "阿拉希"}, {"阿拉索", "阿拉索"},
        {"阿斯塔洛", "阿斯塔洛"}, {"阿曼尼", "阿曼尼"}, {"阿格拉玛", "阿格拉玛"},
        {"阿比迪斯", "阿比迪斯"}, {"阿纳克洛斯", "阿纳克洛斯"}, {"阿迦玛甘", "阿迦玛甘"},
        {"雏龙之翼", "雏龙之翼"}, {"雷克萨", "雷克萨"}, {"雷德", "雷德"}, {"雷斧堡垒", "雷斧堡垒"},
        {"雷霆之怒", "雷霆之怒"}, {"雷霆之王", "雷霆之王"}, {"雷霆号角", "雷霆号角"}, {"霍格", "霍格"},
        {"霜之哀伤", "霜之哀伤"}, {"霜狼", "霜狼"}, {"风暴之怒", "风暴之怒"}, {"风暴之眼", "风暴之眼"},
        {"风暴之鳞", "风暴之鳞"}, {"风暴峭壁", "风暴峭壁"}, {"风暴裂隙", "风暴裂隙"},
        {"风行者", "风行者"}, {"鬼雾峰", "鬼雾峰"}, {"鲜血熔炉", "鲜血熔炉"}, {"鹰巢山", "鹰巢山"},
        {"麦姆", "麦姆"}, {"麦维影歌", "麦维影歌"}, {"麦迪文", "麦迪文"}, {"黄金之路", "黄金之路"},
        {"黑手军团", "黑手军团"}, {"黑暗之矛", "黑暗之矛"}, {"黑暗之门", "黑暗之门"},
        {"黑暗虚空", "黑暗虚空"}, {"黑暗魅影", "黑暗魅影"}, {"黑石尖塔", "黑石尖塔"},
        {"黑翼之巢", "黑翼之巢"}, {"黑铁", "黑铁"}, {"黑锋哨站", "黑锋哨站"}, {"黑龙军团", "黑龙军团"},
        {"龙骨平原", "龙骨平原"},                };


    public static String slugify(String realm, String region) {
        // trim hyphens and apostrophes.
        String slug = "";
        for (int i = 0; i < realm.length(); i++) {
            Character c = realm.charAt(i);
            if (c != '\'' && c != '-') slug += realm.charAt(i);
        }
        // substitute some accentuated characters
        slug = slug.replace(' ', '-').replace('é', 'e');
        slug = slug.replace('й', 'и').replace('ü', 'u');
        // and lower-case it
        slug = slug.toLowerCase();

        return slug;
    }

    public static boolean validate_realm(String slug, String region) {
        String[] realms = eu_realms;
        if (region.equals("us"))
            realms = us_realms;
        else if (region.equals("eu"))
            realms = eu_realms;
        else if (region.equals("tw"))
            realms = tw_realms;
        else if (region.equals("cn"))
            realms = cn_realms;
        else if (region.equals("kr"))
            realms = kr_realms;
        List<String> realms_list = Arrays.asList(realms);

        return (realms_list.contains(slug)) ? true : false;
    }

}
